### ISSUE TITLE
Getting 404 errors 

### ISSUE THREAD

**Issue by MoonWalker440** [mu-fazil-vk/FluxTube#14]
I am getting a error like this whenever I am trying to play a video. Otherwise the app looks clean and super. ![Screenshot_20240724_074713.jpg](https://github.com/user-attachments/assets/7d115670-2686-4b55-8408-3b339813b340)

**Comment by mu-fazil-vk** [comment]
Thank you for your feedback! Are you still experiencing this error when trying to play a video? I'll look into it.

**Comment by MoonWalker440** [comment]
Nope. It got fixed in latest update. Thank you

**Comment by mu-fazil-vk** [comment]
Okay 😊

**Comment by ITfisher** [comment]
i have the same error in version 0.6.9 and not fixed，i dont known why and how to reslove it.

**Comment by mu-fazil-vk** [comment]
@ITfisher check with version [v0.7.0](https://github.com/mu-fazil-vk/FluxTube/releases/tag/v0.7.0). If the problem is still there, try clearing the cache and changing the instance from the settings.
